import { theme } from "@/constants/theme";
import { Dimensions, Platform, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.color.background.dark,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.backgroundElement.dark,
    backgroundColor: theme.color.background.dark,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flex: 1,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerBadge: {
    backgroundColor: theme.color.reactBlue.light,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    marginLeft: 8,
  },
  headerBadgeText: {
    color: theme.color.background.dark,
    fontSize: 10,
    fontWeight: "bold",
  },
  headerButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  headerTitle: {
    fontSize: 24,
    fontFamily: "JetBrainsMono-Medium",
    color: theme.color.reactBlue.light,
  },
  storiesContainer: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.backgroundElement.dark,
  },
  storyWrapper: {
    alignItems: "center",
    marginHorizontal: 8,
    width: 72,
  },
  storyRing: {
    width: 68,
    height: 68,
    borderRadius: 34,
    padding: 2,
    backgroundColor: theme.color.background.dark,
    borderWidth: 2,
    borderColor: theme.color.reactBlue.light,
    marginBottom: 4,
  },
  noStory: {
    borderColor: theme.color.textSecondary.dark,
  },
  viewedStory: {
    borderColor: theme.color.textSecondary.dark,
  },
  storyAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: theme.color.background.dark,
  },
  bheader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    backgroundColor: theme.color.background.dark,
  },

  bheaderTitle: {
    fontSize: 24,
    fontFamily: "JetBrainsMono-Medium",
    color: theme.color.reactBlue.light,
  },
  bheaderRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  storyUsername: {
    fontSize: 11,
    color: theme.colorWhite,
    textAlign: "center",
  },
  post: {
    marginBottom: 16,
  },
  postHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
  },
  postHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  postAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 8,
  },
  postUsername: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colorWhite,
  },
  postImage: {
    width: width,
    height: width,
  },
  postActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  postActionsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  postInfo: {
    paddingHorizontal: 12,
  },
  likesText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colorWhite,
    marginBottom: 6,
  },
  captionContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 6,
  },
  captionUsername: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colorWhite,
    marginRight: 6,
  },
  captionText: {
    fontSize: 14,
    color: theme.colorWhite,
    flex: 1,
  },
  commentsText: {
    fontSize: 14,
    color: theme.color.textSecondary.dark,
    marginBottom: 4,
  },
  timeAgo: {
    fontSize: 12,
    color: theme.color.textSecondary.dark,
    marginBottom: 8,
  },
  modalContainer: {
    backgroundColor: theme.color.background.dark,
    marginBottom: Platform.OS === "ios" ? 44 : 0,
    flex: 1,
    marginTop: Platform.OS === "ios" ? 44 : 0,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    height: 56,
    borderBottomWidth: 0.5,
    borderBottomColor: theme.color.backgroundElement.dark,
  },
  modalTitle: {
    color: theme.colorWhite,
    fontSize: 16,
    fontWeight: "600",
  },
  commentsList: {
    flex: 1,
  },
  commentContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: theme.color.backgroundElement.dark,
  },
  commentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 12,
  },
  commentContent: {
    flex: 1,
  },
  commentUsername: {
    color: theme.colorWhite,
    fontWeight: "500",
    marginBottom: 4,
  },
  commentText: {
    color: theme.colorWhite,
    fontSize: 14,
    lineHeight: 20,
  },
  commentTime: {
    color: theme.color.textSecondary.dark,
    fontSize: 12,
    marginTop: 4,
  },
  commentInput: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 0.5,
    borderTopColor: theme.color.backgroundElement.dark,
    backgroundColor: theme.color.background.dark,
  },
  input: {
    flex: 1,
    color: theme.colorWhite,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginRight: 12,
    backgroundColor: theme.color.backgroundElement.dark,
    borderRadius: 20,
    fontSize: 14,
  },
  postButton: {
    color: theme.color.reactBlue.light,
    fontWeight: "600",
    fontSize: 14,
  },
  postButtonDisabled: {
    opacity: 0.5,
  },
  centered: {
    justifyContent: "center",
    alignItems: "center",
  },
  feedContainer: {
    paddingBottom: 80,
  },
  postSeparator: {
    height: 1,
    backgroundColor: theme.color.backgroundElement.dark,
    marginHorizontal: 16,
  },
  noPostsContainer: {
    flex: 1,
    backgroundColor: theme.color.background.dark,
  },
  noPostsGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  noPostsContent: {
    alignItems: "center",
    maxWidth: 320,
  },
  noPostsIconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#111111",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
    borderWidth: 2,
    borderColor: "#222222",
  },
  noPostsTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: theme.colorWhite,
    marginBottom: 12,
    textAlign: "center",
  },
  noPostsSubtitle: {
    fontSize: 16,
    color: theme.color.textSecondary.dark,
    textAlign: "center",
    marginBottom: 32,
    lineHeight: 24,
  },
  createPostButton: {
    borderRadius: 25,
    overflow: "hidden",
    shadowColor: theme.color.reactBlue.light,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  createPostGradient: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 14,
    backgroundColor: theme.colorWhite,
  },
  createPostText: {
    color: theme.colorBlack,
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  emptyStateContainer: {
    alignItems: "center",
    paddingHorizontal: 32,
    maxWidth: 320,
  },
  emptyIconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#111111",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
    borderWidth: 2,
    borderColor: "#222222",
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: theme.colorWhite,
    marginBottom: 12,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 16,
    color: theme.color.textSecondary.dark,
    textAlign: "center",
    lineHeight: 24,
  },
  bookmarkImageContainer: {
    position: "relative",
    borderRadius: 8,
    overflow: "hidden",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  bookmarkImage: {
    width: "100%",
    aspectRatio: 1,
  },
  bookmarkOverlay: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    borderRadius: 12,
    padding: 4,
  },
});
