import { StyleSheet, Dimensions } from "react-native";
import { theme } from "@/constants/theme";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.color.background.dark,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.color.background.dark,
  },
  loadingText: {
    color: theme.colorWhite,
    fontSize: 16,
    marginTop: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.color.background.dark,
    paddingHorizontal: 32,
  },
  errorTitle: {
    color: theme.colorWhite,
    fontSize: 24,
    fontWeight: "bold",
    marginTop: 16,
    textAlign: "center",
  },
  errorSubtitle: {
    color: theme.color.textSecondary.dark,
    fontSize: 16,
    marginTop: 8,
    textAlign: "center",
    lineHeight: 24,
  },
  retryButton: {
    backgroundColor: theme.colorWhite,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 24,
  },
  retryButtonText: {
    color: theme.colorBlack,
    fontSize: 16,
    fontWeight: "600",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: theme.color.backgroundElement.dark,
  },
  headerLeft: {
    flex: 1,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerIcon: {
    padding: 8,
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    color: theme.color.reactBlue.light,
    fontSize: 24,
    fontFamily: "JetBrainsMono-Medium",
  },
  scrollView: {
    flex: 1,
  },
  profileSection: {
    padding: 16,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  avatarContainer: {
    position: "relative",
    marginRight: 24,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: theme.colorWhite,
  },
  addStoryButton: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.color.reactBlue.light,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: theme.color.background.dark,
  },
  statsContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  statItem: {
    alignItems: "center",
  },
  statNumber: {
    color: theme.colorWhite,
    fontSize: 18,
    fontWeight: "bold",
  },
  statLabel: {
    color: theme.color.textSecondary.dark,
    fontSize: 14,
    marginTop: 4,
  },
  userInfo: {
    marginBottom: 16,
  },
  displayName: {
    color: theme.colorWhite,
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  username: {
    color: theme.color.textSecondary.dark,
    fontSize: 14,
    marginBottom: 8,
  },
  name: {
    color: theme.colorWhite,
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 4,
  },
  bio: {
    color: theme.colorWhite,
    fontSize: 14,
    lineHeight: 20,
  },
  actionButtons: {
    flexDirection: "row",
    marginBottom: 16,
  },
  followButton: {
    flex: 1,
    backgroundColor: theme.color.reactBlue.light,
    paddingVertical: 12,
    borderRadius: 8,
    marginRight: 8,
    alignItems: "center",
  },
  unfollowButton: {
    backgroundColor: theme.color.backgroundElement.dark,
    borderWidth: 1,
    borderColor: theme.color.textSecondary.dark,
  },
  followButtonText: {
    color: theme.colorWhite,
    fontSize: 16,
    fontWeight: "600",
  },
  unfollowButtonText: {
    color: theme.colorWhite,
  },
  messageButton: {
    flex: 1,
    backgroundColor: theme.color.backgroundElement.dark,
    paddingVertical: 12,
    borderRadius: 8,
    marginLeft: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.color.textSecondary.dark,
  },
  messageButtonText: {
    color: theme.colorWhite,
    fontSize: 16,
    fontWeight: "600",
  },
  editProfileButton: {
    backgroundColor: theme.color.backgroundElement.dark,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.color.textSecondary.dark,
  },
  editProfileButtonText: {
    color: theme.colorWhite,
    fontSize: 16,
    fontWeight: "600",
  },
  storiesSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    color: theme.colorWhite,
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  storiesContainer: {
    paddingHorizontal: 16,
  },
  storyItem: {
    marginRight: 12,
  },
  storyThumbnail: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: theme.color.reactBlue.light,
  },
  postsSection: {
    marginBottom: 24,
  },
  postsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 16,
  },
  postItem: {
    width: (width - 48) / 3,
    height: (width - 48) / 3,
    marginRight: 6,
    marginBottom: 6,
  },
  postThumbnail: {
    width: "100%",
    height: "100%",
    borderRadius: 4,
  },
  emptyPostsContainer: {
    alignItems: "center",
    paddingVertical: 48,
    paddingHorizontal: 32,
  },
  emptyPostsText: {
    color: theme.colorWhite,
    fontSize: 18,
    fontWeight: "600",
    marginTop: 16,
    textAlign: "center",
  },
  emptyPostsSubtext: {
    color: theme.color.textSecondary.dark,
    fontSize: 14,
    marginTop: 8,
    textAlign: "center",
  },
  createPostButton: {
    backgroundColor: theme.color.reactBlue.light,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 16,
  },
  createPostButtonText: {
    color: theme.colorWhite,
    fontSize: 16,
    fontWeight: "600",
  },
  profileInfo: {
    paddingVertical: 20,
  },
  avatarAndStats: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    paddingHorizontal: 16,
  },
  editButton: {
    flex: 1,
    backgroundColor: theme.color.backgroundElement.dark,
    paddingVertical: 12,
    borderRadius: 8,
    marginRight: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.color.textSecondary.dark,
  },
  editButtonText: {
    color: theme.colorWhite,
    fontSize: 16,
    fontWeight: "600",
  },
  shareButton: {
    width: 48,
    height: 48,
    backgroundColor: theme.color.backgroundElement.dark,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.color.textSecondary.dark,
  },
  postsHeader: {
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  postsTitle: {
    color: theme.colorWhite,
    fontSize: 18,
    fontWeight: "600",
  },
  gridItem: {
    width: (width - 48) / 3,
    height: (width - 48) / 3,
    marginRight: 6,
    marginBottom: 6,
  },
  gridImage: {
    width: "100%",
    height: "100%",
    borderRadius: 4,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: theme.color.backgroundElement.dark,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    color: theme.colorWhite,
    fontSize: 20,
    fontWeight: "600",
  },
  inputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    color: theme.colorWhite,
    fontSize: 16,
    marginBottom: 8,
  },
  input: {
    backgroundColor: theme.color.background.dark,
    borderRadius: 8,
    padding: 12,
    color: theme.colorWhite,
    fontSize: 16,
    borderWidth: 1,
    borderColor: theme.color.textSecondary.dark,
  },
  bioInput: {
    height: 80,
    textAlignVertical: "top",
  },
  saveButton: {
    backgroundColor: theme.color.reactBlue.light,
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
  },
  saveButtonText: {
    color: theme.colorWhite,
    fontSize: 16,
    fontWeight: "600",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  postDetailContainer: {
    width: "90%",
    height: "80%",
  },
  postDetailHeader: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: 20,
  },
  postDetailImage: {
    width: "100%",
    height: "100%",
    borderRadius: 8,
  },
});
